SPARKNLP-261 end to end simple example
There is an error seem to be related to the shape of the audio (Array[Float])

```
org.tensorflow.exceptions.TFUnimplementedException: Fused conv implementation does not support grouped convolutions for now.
	 [[{{function_node __inference_serving_142503}}{{node wav2vec2/encoder/pos_conv_embed/conv/TFWav2Vec2WeightNormConv1D}}]]
```